Adição de candidaturas
desenvolvendo-me/applify pull request #33
Opened 2023-11-30 23:53 UTC by daniel-neves-dev

Criado formulário para adição de candidaturas

2023-12-04 22:03 UTC, PhilipeeX commented on db/schema.rb
N precisa commitar o schema

2023-12-04 22:08 UTC, PhilipeeX commented on app/helpers/candidatures_helper.rb
YAGN, remover o que não for usar

2023-12-04 22:19 UTC, PhilipeeX commented on app/views/candidatures/_form.html.erb
> +      <%= f.input :situation, collection: [:send, :sending, :answered], prompt: :translate %>
O ideal seria usar um `enum` para o select

2023-12-04 22:24 UTC, PhilipeeX commented on app/helpers/candidatures_helper.rb
YAGN, remover arquivos que não estão sendo usados

2023-12-04 22:24 UTC, PhilipeeX commented on app/views/candidatures/_form.html.erb
> +      <%= f.input :situation, collection: [:send, :sending, :answered], prompt: :translate %>
esse select seria ideal usar um `enum`

2023-12-06 13:59 UTC, cassiosantana requested changes

2023-12-06 13:59 UTC, cassiosantana commented on config/locales/candidatures/pt-BR.yml
> +          situation_not_chosen: "Nenuma situação foi escolhida"
Corrigir a palavra "Nenuma".

2023-12-06 13:59 UTC, cassiosantana commented on spec/requests/candidatures_spec.rb
Remover teste de request.

2023-12-06 13:59 UTC, cassiosantana commented on spec/routing/candidatures_routing_spec.rb
Remover teste de routing

2023-12-06 14:02 UTC, cassiosantana commented on app/controllers/manager/candidatures_controller.rb
> +  class CandidaturesController < InheritedResources::Base
Este controller não deveria herdar de Internal?

2023-12-07 14:54 UTC, daniel-neves-dev commented on spec/requests/candidatures_spec.rb
Não vejo sentido em remover os testes

2023-12-07 17:22 UTC, closed without merging