Formulário de candidaturas
desenvolvendo-me/applify pull request #40
Opened 2023-12-07 23:48 UTC by daniel-neves-dev

Atualizado os testes

2023-12-08 13:39 UTC, PhilipeeX approved these changes

2023-12-08 13:39 UTC, PhilipeeX commented on app/helpers/candidatures_helper.rb
> +end
YAGN, remover arquivos não utilizados

2023-12-08 13:46 UTC, marcodotcastro commented on app/controllers/manager/candidatures_controller.rb
> +      redirect_to manager_candidatures_path
Pra que serve esse código?

2023-12-08 13:50 UTC, marcodotcastro commented on app/views/manager/candidatures/_candidature.html.erb
Não é essa a identidade da aplicação

2023-12-08 13:50 UTC, marcodotcastro commented on app/views/manager/candidatures/index.html.erb
Não é essa a identidade da aplicação

2023-12-08 13:52 UTC, marcodotcastro commented on spec/factories/candidatures.rb
> +    sequence(:company_name) { |n| "Rails Vacancy #{n}" }
Use dados mais reais nos testes

2023-12-08 13:52 UTC, marcodotcastro commented on spec/features/manager/candidatures_feature_spec.rb
Use dados mais reais nos testes

2023-12-08 13:53 UTC, marcodotcastro requested changes
Está faltando os testes de model.

2023-12-09 12:48 UTC, ricardofelipe7 commented on config/locales/controllers/manager/candidatures.pt-BR.yml
> +      destroy: " deletada com sucesso"
Mantem o padrão. "Candidatura atualizada com sucesso."

2023-12-09 12:50 UTC, ricardofelipe7 commented on config/locales/views/layouts/external.pt-BR.yml
Tem que ser movido para INTERNAL.

2023-12-18 12:00 UTC, marcodotcastro approved these changes

2023-12-18 12:00 UTC, merged