Feature/35 simulado funcionalidades interativas
desenvolvendo-me/applify pull request #59
Opened 2023-12-18 18:26 UTC by PhilipeeX

2023-12-18 19:14 UTC, marcodotcastro requested changes
Crie test para o helper

2023-12-22 17:24 UTC, ricardo-benicio approved these changes

2024-01-03 12:20 UTC, cassiosantana commented on app/views/job_simulations/_upload_file.html.erb
> +      <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold"><%= I18n.t('views.defaults.upload_file.click_to_send') %></span> <%= t 'views.defaults.upload_file.drag_and_
Seguir convenção i18n "Lazy Lookup"

2024-01-04 17:25 UTC, marcodotcastro approved these changes

2024-01-04 17:25 UTC, merged