57-nao-permitir-excluir-a-empresa-caso-esteja-sendo-usada
desenvolvendo-me/applify pull request #65
Opened 2024-01-05 14:26 UTC by ricardo-benicio

2024-01-05 17:54 UTC, marcodotcastro requested changes
Está faltando teste no PR

2024-01-09 19:57 UTC, marcodotcastro commented on db/migrate/20231213212720_create_active_storage_tables.active_storage.rb
Porque isso foi removido?

2024-01-09 19:58 UTC, marcodotcastro commented on spec/factories/candidatures.rb
> +    company_id { create(:company) }
Você deixar o somente assim:
`company`
no lugar de:
`company_id { create(:company) }`

2024-01-09 20:00 UTC, marcodotcastro commented on app/views/manager/candidatures/_candidature.html.erb
> +    <input type="checkbox" id="<%= candidature %>-checkbox" data-goals--index-target="checkbox" value="<%= candidature.id %>">
Porque foi removido o método convert_to_id ?

2024-01-09 20:00 UTC, marcodotcastro reviewed
Segue alguns comentários

2024-01-09 20:43 UTC, closed without merging

2024-01-10 11:48 UTC, ricardo-benicio commented on db/migrate/20231213212720_create_active_storage_tables.active_storage.rb
a migração estava duplicada na pasta migrate.

2024-01-10 11:49 UTC, ricardo-benicio commented on spec/factories/candidatures.rb
> +    company_id { create(:company) }
Ok

2024-01-10 11:50 UTC, ricardo-benicio commented on app/views/manager/candidatures/_candidature.html.erb
> +    <input type="checkbox" id="<%= candidature %>-checkbox" data-goals--index-target="checkbox" value="<%= candidature.id %>">
Não estava passando o teste por causa deste método.

![Screenshot from 2024-01-09 18-35-34](https://github.com/desenvolvendo-me/applify/assets/65983088/fea21a22-505f-46f9-9378-d81902d87ca7)